---
- name: "Install OpenHPC 3.x w/Warewulf 4.x"
  hosts: LoginNodes
  user: labadm
  become: true
  gather_facts: false
  vars:
    ohpc_version: "3"
    ohpc_rev: "1"
  tasks:
    - name: Disable stop and disable firewalld
      ansible.builtin.systemd_service:
        state: stopped
        enabled: false
        name: firewalld
    - name: Installing OpenHPC-3 GPG Key
      ansible.builtin.rpm_key:
        state: present
        key: https://raw.githubusercontent.com/openhpc/ohpc/8b0fbb5ec130cb949900aca73e2f27a9b4113ced/components/admin/ohpc-release/SOURCES/RPM-GPG-KEY-OpenHPC-3
    - name: Install the OpenHPC Repo
      ansible.builtin.yum:
        name:
          - epel-release
          - 'http://repos.openhpc.community/OpenHPC/{{ ohpc_version }}/EL_9/x86_64/ohpc-release-{{ ohpc_version }}-{{ ohpc_rev }}.el9.x86_64.rpm'
        state: present
